package lab2exercise2;

import java.util.Random;

public class Lotto {
    private int[] generatedArray;  // stores int values generated by the computer

    public Lotto() {
        Random random = new Random();
        generatedArray = new int[3];  // array to hold 3 random numbers

        // generates random numbers from 1 to 9
        generatedArray[0] = random.nextInt(9) + 1;
        generatedArray[1] = random.nextInt(9) + 1;
        generatedArray[2] = random.nextInt(9) + 1;
    }

    // getter to return the array generated by the computer
    public int[] getGeneratedArray() {
        return generatedArray;
    }

    // method to calculate and return the sum of the lotto numbers
    public int getLottoSum() {
        return generatedArray[0] + generatedArray[1] + generatedArray[2];
    }
}

